### PR TITLE
Working

### PR DESCRIPTION
**Pull request by jamesvrt**
Before you submit a pull request, please fill in the following:

**Related Issue(s):**
https://github.com/stactools-packages/nalcms/issues/3

**Description:**
Completed the development of NALCMS STAC structural code and populated the appropriate constants. Included STAC extensions as necessary.

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [x] Documentation has been updated to reflect changes, if applicable.
- [x] Changes are added to the [CHANGELOG](../CHANGELOG.md).

### CODE REVIEW

**Comment by jamesvrt** [comment]
Getting the following bug when saving the catalog:

`TypeError: Object of type datetime is not JSON serializable`

If I convert datetimes to strings then I get an error that strings don't have the property of `tzinfo`. I'll come back to look at this in two weeks.

**Comment by jamesvrt** [comment]
There's a conflict between `mypy` typing requirements and GH CI typing requirements resulting in:

```
src/stactools/nalcms/commands.py:3: error: unused "type: ignore" comment
```

Any suggestions on how to circumvent this?

**Review by bluegeo — COMMENTED** [review]
I didn't quite finish this before heading out on vacation (and I see that this has already been merged), but one thing I should have noted is that the `create_cog` method should make use of `stactools.core.utils.convert.cogify`. I will create an issue.

**Comment by jamesvrt** [comment]
Sorry, I've only just realised I merged before you completed your review. Thanks for taking a look - agreed about the `create_cog` method.

**Pull request merged**
